data:
  validate_db:
    cif_db_path: /NHNHOME/WORKSPACE/0226010152_A/data/v2/cif_attached_train_20260224_res9_chain300.lmdb
    a3m_db_path: /NHNHOME/WORKSPACE/0226010152_A/data/a3m_16k.lmdb
    edge_id_to_bias_path: /NHNHOME/WORKSPACE/0226010152_A/data/v2/metadata/train_20260224_edge_node.tsv
    template_db_path: /NHNHOME/WORKSPACE/0226010152_A/data/template.lmdb
    ccd_preprocessed_path: /NHNHOME/WORKSPACE/0226010152_A/data/CCD/preprocessed_CCD.lmdb
  crop:
    max_tokens: 384
    max_atoms: 4096
    min_segment_size: 1
    max_segment_size: 41
    monomer_only: false
    remain_invalid_tokens: false
    bucket_msa_size: 128
    bucket_token_size: 128
    bucket_atom_size: 1024
    chain_crop_prob: 0.5
  msa:
    n_samples: 1
    max_msa_depth: 384
    missing_policy: query
  tokenizer:
    level: dynamic
    dynamic_tokenization:
      minimum_resolution_ratio:
      - 0.2
      - 0.6
      - 0.2
      sigma_flat_prob: 0.0
      sigma_min: 4.0
      sigma_max: 8.0
validation:
  seed: 0
  num_samples: 4
  timesteps: 100
  num_workers: 0
  compile: false
  use_ema: true
model:
  shared:
    d_single: 384
    d_single_atom: 128
    d_single_token: 768
    d_single_token_input: 449
    d_pair: 128
    d_pair_template: 128
    d_pair_atom: 16
    d_contact: 3
    d_time: 256
    r_max: 32
    s_max: 2
    dgram_bins_template: 39
    relpos_bins: 32
    noise_freq: 256
    num_res_class: 32
    n_distogram_bins: 64
    implementation: triton
    use_checkpoint: false
  input_feat_embbeder:
    d_single: 128
    d_cond: 128
    d_pair: 16
    n_head: 4
    use_qk_norm: false
    implementation: triton
    n_block: 3
    n_checkpoint_segments: null
    kernel_type: compute_efficient
  trunk:
    pairformer:
      d_single: 384
      d_pair: 128
      n_head_tri_attention: 4
      n_head_attention: 16
      p_drop: 0.25
      use_self_attention: false
      use_qk_norm: false
      implementation: cuequivariance
      n_block: 48
      n_checkpoint_segments: 8
    msa_module:
      d_msa: 64
      d_pair: 128
      d_single_token_input: 449
      d_hidden_msa: 32
      d_hidden_tri_multi: 128
      d_hidden_tri_attention: 32
      n_head_tri_attention: 4
      n_head_attention: 16
      p_drop_msa: 0.15
      p_drop: 0.25
      use_self_attention: false
      implementation: cuequivariance
      num_res_class: 32
      n_block: 4
      n_checkpoint_segments: null
    template_embedder:
      d_pair_template_input: 4
      d_pair: 128
      d_hidden: 128
      n_head_tri_attention: 4
      p_drop: 0.25
      use_self_attention: false
      implementation: cuequivariance
      n_block: 2
      dropout_prob: 0.25
    n_recycle_max: 4
  diffusion:
    atom_dit:
      d_single: 128
      d_cond: 128
      d_pair: 16
      n_head: 4
      use_qk_norm: false
      implementation: triton
      n_block: 3
      n_checkpoint_segments: 3
      kernel_type: memory_efficient
    token_dit:
      d_single: 768
      d_cond: 384
      d_pair: 128
      n_head: 24
      use_qk_norm: false
      implementation: triton
      n_block: 24
      n_checkpoint_segments: 6
      kernel_type: memory_efficient
    dit_cond:
      n_expand: 2
      n_blocks: 2
diffuser:
  seed: 0
  translation_noise: 1.0
  max_loss_weight: 1000.0
  scheduler:
    method: AF3
    P_mean: -1.5
    P_std: 1.8
    sigma_data: 16.0
    sigma_y_max: 160.0
    sigma_y_min: 0.0004
    rho_y: 7.0
    sigma_y_phase_1_boundary: 64.0
    sigma_y_phase_2_boundary: 0.01
    smooth_phase_transition: true
    sigma_R_max: 3.0
    sigma_R_min: 0.01
    rho_R: 3.0
    sigma_T_max: 8.0
    sigma_T_min: 4.0e-06
    rho_T: 3.0
    use_time_augmentation: true
  solver:
    seed: 0
    gamma_0: 0.8
    gamma_min: 1.0
    noise_lambda: 1.003
    step_scale: 1.5
loss:
  diffusion_loss: 2.0
  distogram_loss: 0.03
  smooth_lddt_loss: 0.0
