# -*- coding: utf-8 -*-
"""Token DiT attention: training forward / backward and the fused inference block, in the house style of
msa_opm/MSA_OPM_FORWARD.svg (helpers taken from generate_msa_svg.py without running its figures).

Run: python docs/kernels/generate_token_dit_svg.py   (writes token_dit/ beside this file)
"""
import os

_here = os.path.dirname(os.path.abspath(__file__))
_src = open(os.path.join(_here, "generate_msa_svg.py"), encoding="utf-8").read()
exec(_src.split("\nOUT = ")[0])                                    # T, wrap, box, row, doc -- no figures emitted
OUT = os.path.join(_here, "token_dit") + "/"

# ------------------------------------------------------------------ TRAINING FORWARD (measured)
doc(OUT + "TOKEN_DIT_ATTN_TRAIN_FORWARD.svg",
    "Token DiT attention  TRAINING FORWARD  |  HBM 입력 → 커널 → HBM 출력",
    "L768 · A=48 augment · 16 heads × 48 · fp32 모델, 어텐션 코어만 bf16 (fp32 누산) · H100 실측",
    ["pair bias는 24블록 전부를 한 GEMM으로 먼저 만든다 (hoist). 블록마다 LayerNorm + Linear를 반복하지 않는다.",
     "코어는 bias를 누산기 초기값으로 넣고(seed) QKᵀ wgmma가 그 위에 누산한다 — bias 덧셈이 사라진다. exp는 전부 ex2 한 번.",
     "코어 334 µs = 수학 뺀 같은 데이터 이동의 실측 하한 273 µs의 82 %. 엔진 bf16 코어 fwd 658.8 µs, Anthropic은 학습 fwd 없음."],
    [
     ("pair-bias hoist · 한 스텝에 한 번 · team-gm pair_bias_all(head_major=True)",
      ["pair: FP32 [1,768,768,128] 302 MB", "γ_b (ln_pair), W_b (to_bias) × 24블록", "각 [128], [16,128]"],
      ["ln_pair에는 offset이 없어서 LN_b(pair) = LN0(pair) ⊙ γ_b",
       "→ bias_b = LN0(pair) · (γ_b ⊙ W_b)ᵀ, 24블록 모두 같은 LN0",
       "γ를 weight 쪽에 접어 넣고 24 × 16 = 384행을 쌓아 GEMM 하나",
       "출력을 head-major로 내서 코어가 permute 없이 읽는다",
       "── 수식 ──",
       "B = Wf · LN0(pair)ᵀ,   Wf = [γ_1⊙W_1; … ; γ_24⊙W_24]"],
      ["ln0 = layer_norm(pair.reshape(-1,128), (128,))",
       "wf  = cat([w * g for g, w in zip(G, W)])",
       "B   = wf @ ln0.t()                   # [384, L*L]",
       "bias_b = B[16*b:16*(b+1)].view(16,1,L,L)",
       "# 블록마다: layer_norm + Linear 24번 -> 0번"],
      ["B: FP32 [384, 589,824] 906 MB", "블록 b는 16행짜리 view (복사 없음)", "→ bias_prep"]),

     ("prep_qkv (Triton) · 85 µs",
      ["q (qk_norm 뒤): FP32 [48,1,768,16,48] 113 MB", "k: FP32 113 MB", "v: FP32 113 MB"],
      ["한 패스로 세 텐서를 bf16으로 변환",
       "q에는 log2(e)/√48을 같이 곱한다 — 코어의 점수가 곧 log2 단위라서",
       "softmax의 exp가 전부 ex2 하나로 끝난다",
       "── 수식 ──",
       "q_s = bf16(q · log2e / √48),   k_b = bf16(k),   v_b = bf16(v)"],
      ["qs = (q * (LOG2E / sqrt(48))).bfloat16()",
       "kb = k.bfloat16();  vb = v.bfloat16()",
       "# 모두 [A*L, 768] 행 레이아웃 그대로"],
      ["q_s, k_b, v_b: BF16 [36,864, 768] 각 56.6 MB", "→ attn_fwd, backward용 저장"]),

     ("bias_prep (Triton) · 미측정",
      ["bias_b: FP32 [16,768,768] 37.7 MB (hoist view)"],
      ["log2(e)를 곱해 bf16으로 — 코어가 bias를 변환 없이 누산기에 넣을 수 있게",
       "── 수식 ──",
       "b_b = bf16(bias · log2e)"],
      ["bb = (bias.view(16, L, L) * LOG2E).bfloat16()"],
      ["bb: BF16 [16,768,768] 18.9 MB", "→ attn_fwd, backward용 저장"]),

     ("attn_fwd (CUDA sm_90a, attn_fwd.cu) · 334 µs · pattern floor 273 µs → 82 %",
      ["q_s 56.6 MB (CTA당 한 번)", "k_b, v_b 각 56.6 MB (query 타일 6개가 재사용 → L2)", "bb 18.9 MB (48 샘플이 같은 타일 → L2)", "key mask (있을 때)"],
      ["CTA = (샘플, head, query 128행), 샘플이 grid의 가장 빠른 축",
       "→ 같은 bias 타일을 쓰는 48개 CTA가 동시에 떠서 bias는 L2에서 읽힌다",
       "TMA 3개(K, V, bias) → 3단 ring · q는 레지스터에 한 번",
       "q/k/v 박스는 48열 — 이웃 head 16열을 더 읽지 않는다 (−25 % 바이트)",
       "key 블록 64개마다: bias를 누산기에 seed → QKᵀ wgmma가 그 위에 누산",
       "lazy max: 행 최댓값이 8(log2) 넘게 오를 때만 누산기를 rescale",
       "ex2 → P(bf16) → PV wgmma (A=레지스터, B=V smem)",
       "── 수식 ──",
       "S = q_s k_bᵀ + b_b (+ mask),   m = 행 max,   P = 2^(S−m)",
       "O = P v / Σ P,   LSE = m + log2 Σ P   (log2 단위)"],
      ["s = (q @ k.transpose(-1,-2)) / sqrt(48) + bias",
       "if mask is not None:",
       "    s = s.masked_fill(~mask, finfo.min)",
       "lse = torch.logsumexp(s, -1)",
       "o = torch.softmax(s, -1) @ v",
       "# [48,16,768,768] 점수는 HBM에 안 나간다"],
      ["O: FP32 [36,864, 768] 113 MB", "LSE: FP32 [48,16,768] 2.4 MB", "→ gate · to_out (fp32)", "→ backward용 저장 (O는 gate가 잡은 것과 공유)"]),
    ])

# ------------------------------------------------------------------ TRAINING BACKWARD (measured)
doc(OUT + "TOKEN_DIT_ATTN_TRAIN_BACKWARD.svg",
    "Token DiT attention  TRAINING BACKWARD  |  HBM 입력 → 커널 → HBM 출력",
    "L768 · A=48 · bf16 코어 · H100 실측 bwd 1,507 µs (dQ+dbias 951 + dK/dV 556) · 엔진 bf16 bwd ~3,977 µs, Anthropic은 backward 없음",
    ["세 가지 축약의 축이 다르다: dK·dV는 query 축, dQ는 key 축, dbias는 샘플 축 (bias를 48 샘플이 공유).",
     "dbias를 샘플마다 L2 atomic으로 더하면 ~680 µs. dQ 커널의 워프그룹 3개를 서로 다른 샘플로 두고 smem에서 먼저 합쳐 atomic을 1/3로 줄였다.",
     "저장은 bf16 q/k/v · bias, fp32 O · LSE만. 점수 [48,16,768,768]는 fwd·bwd 어디에서도 HBM에 나가지 않는다 (재계산)."],
    [
     ("saved tensors · forward가 남긴 것 (체크포인트 재계산 때만)",
      ["q_s, k_b, v_b: BF16 각 56.6 MB", "bb: BF16 18.9 MB", "O: FP32 113 MB (gate 입력과 공유)", "LSE: FP32 2.4 MB"],
      ["P는 저장하지 않는다 — [48,16,768,768] bf16이면 906 MB",
       "LSE가 있으면 P = 2^(S − LSE)로 정규화까지 끝난 값을 바로 재계산한다",
       "fp32 q/k/v는 남지 않는다 (RMSNorm·Linear backward는 입력만 저장)",
       "no_grad에서는 아무것도 남지 않는다 (실측 0.0 MB)"],
      ["ctx.save_for_backward(qs, kb, vb, bb, km, o, lse)",
       "# P, dP, dS: 저장 안 함 -> 커널 안에서 재계산"],
      ["L768 fwd+bwd peak 6.59 GB", "(엔진 bf16 코어 8.50 GB — 샘플별 dbias 1.8 GB)"]),

     ("prep_do (Triton) · 미측정",
      ["dO: FP32 [36,864, 768] 113 MB", "O: FP32 113 MB"],
      ["한 패스로 dO를 bf16으로 바꾸고, head별 행 합 D를 같이 낸다",
       "── 수식 ──",
       "D[a,h,i] = Σ_d dO[a,i,h,d] · O[a,i,h,d]"],
      ["dob = do.bfloat16()",
       "D = (do * o).view(A,L,16,48).sum(-1).transpose(1,2)"],
      ["dO_b: BF16 56.6 MB", "D: FP32 [48,16,768] 2.4 MB", "→ attn_dqb, attn_dkv"]),

     ("attn_dqb (CUDA, attn_dqb.cu) · 951 µs · dQ + dbias",
      ["q_s, dO_b: CTA당 샘플 3개 × 64행", "k_b, v_b: 샘플 3개분 key 블록 스트림", "bb: 64 query × 64 key 타일 (3 샘플이 공유)", "LSE, D"],
      ["CTA = (샘플 3개, head, query 64행) · 워프그룹 w = 샘플 a0+w",
       "각 워프그룹이 자기 샘플의 K/V로 key 블록을 돌고 bias 타일은 셋이 공유",
       "key 블록마다: S 재계산(bias−LSE seed) → P = 2^S → dP = dO Vᵀ → dS",
       "dQ += dS K (레지스터 누산)",
       "dS(fp32)를 smem 교환 버퍼에 → named barrier → 담당 워프그룹이 3개를 합쳐 L2 red",
       "→ atomic 수 1/3 (샘플별 atomic 1,262 µs 경로보다 bwd 합 −200 µs)",
       "── 수식 ──",
       "P = 2^(S − LSE),  dS = P ⊙ (dP − D)",
       "dQ = dS K / √48,   dbias += Σ_{3 샘플} dS"],
      ["p  = torch.exp2(s2 - lse[..., None])",
       "dp = do @ v.transpose(-1,-2)",
       "ds = p * (dp - D[..., None])",
       "dq = ds @ k / sqrt(48)",
       "dbias = ds.sum(0)          # 샘플 축 축약"],
      ["dQ: FP32 [36,864, 768] 113 MB", "dbias: FP32 [16,768,768] 37.7 MB (red.global.add)", "→ RMSNorm backward / hoist backward"]),

     ("attn_dkv (CUDA, attn_dkv.cu, DBIAS=0) · 556 µs · pattern floor 431 µs → 77 %",
      ["k_b, v_b: 128 key → 레지스터에 한 번", "q_s, dO_b: query 블록 64개씩 스트림", "bb: [64 query × 64 key] × 2 워프그룹", "LSE, D"],
      ["CTA = (샘플, head, key 128개) · 워프그룹마다 key 64개가 M 차원",
       "Sᵀ = K Qᵀ를 key가 행인 채로 계산 — P·dS가 그대로 dV·dK의 A 피연산자",
       "bias 타일은 ldmatrix.trans로 전치해 Sᵀ 누산기에 seed",
       "슬롯은 1 KB 정렬 (128B swizzle 요구 — 어긋나면 값이 틀린다)",
       "── 수식 ──",
       "Pᵀ = 2^(Sᵀ − LSE),  dSᵀ = Pᵀ ⊙ (dPᵀ − D)",
       "dV = Pᵀ dO,   dK = dSᵀ Q / √48"],
      ["dv = p.transpose(-1,-2) @ do",
       "dk = ds.transpose(-1,-2) @ q / sqrt(48)"],
      ["dK, dV: FP32 [36,864, 768] 각 113 MB", "→ RMSNorm(k) backward, to_value backward"]),

     ("hoist backward · 한 스텝에 한 번 · GEMM 2 + LN backward 1",
      ["dbias × 24블록 → [384, 589,824] FP32 906 MB (cat)", "pair 302 MB", "γ_b, W_b"],
      ["24블록의 dbias를 한 번에 모아 GEMM 두 개로 끝낸다",
       "γ를 weight에 접었으므로 product rule로 풀어낸다",
       "── 수식 ──",
       "dLN0 = gᵀ Wf,   dWf = g · LN0",
       "dW_b = dWf_b ⊙ γ_b,   dγ_b = Σ_h dWf_b ⊙ W_b",
       "dpair = LN0_bwd(dLN0)"],
      ["g    = cat(dbias_list, 0)       # [384, L*L]",
       "dln0 = g.t() @ wf",
       "dwf  = g @ ln0",
       "dW_b     = dwf_b * gamma_b",
       "dgamma_b = (dwf_b * W_b).sum(0)"],
      ["dpair: FP32 302 MB", "dγ_b, dW_b × 24"]),
    ])

# ------------------------------------------------------------------ INFERENCE BLOCK (measured)
doc(OUT + "TOKEN_DIT_INFERENCE_FUSED.svg",
    "Token DiT  INFERENCE (fused v6)  |  한 블록 · HBM 입력 → 커널 → HBM 출력",
    "L768 · S=5 샘플 · bf16 · 블록 147.8 µs (엔진 1,673.6 / Anthropic 조합 301.9 / Anthropic+hoist 232.0) · 24블록 = 샘플링 한 스텝",
    ["블록당 커널 6개: GEMM 4 + 어텐션 코어 1 + row 패스 2(잔차·gate·다음 AdaLN 융합). 모두 PDL로 이어져 앞 커널 꼬리와 겹친다.",
     "pair bias와 conditioning은 샘플·블록과 무관한 부분을 스텝마다 한 번만 계산한다 (hoist 74.8 µs / 샘플).",
     "커널별 시간은 단독 do_bench(L2 비움) — 한 스텝 안에서는 L2 재사용으로 더 짧다 (코어 45.6 → 40.8 µs)."],
    [
     ("스텝마다 한 번 · pair-bias hoist + conditioning",
      ["pair: [768,768,128]", "cond: [768,384] (샘플 공통)", "24블록의 γ_b⊙W_b, conditioning weight"],
      ["pair bias: 24블록 전부를 GEMM 하나로, head-major bf16, log2(e)까지 접어서",
       "conditioning: 샘플 5개가 같은 cond를 쓰므로 행 L개만 계산해 row-modulo로 읽는다",
       "sigmoid는 row 커널이 읽으면서 적용 (메모리 바운드라 공짜)",
       "── 수식 ──",
       "B = Wf · LN0(pair)ᵀ · log2e,   g1, g2 = LN(cond) W1, cond W2"],
      ["bias = (wf @ ln0.t() * LOG2E).bfloat16()",
       "g1 = layer_norm(c) @ W1.T + b1   # [L, 24*4*768]",
       "g2 = c @ W2.T + b2               # [L, 24*2*768]"],
      ["bias: BF16 [384,768,768] 453 MB", "g1, g2: [768, 24×6×768]", "→ 모든 블록"]),

     ("q|k|v|g GEMM (quack) · 32.8 µs · floor 25.3 → 77 %",
      ["xa: BF16 [3,840, 768] 5.9 MB (AdaLN 적용된 입력)", "W_qkvg: BF16 [3,072, 768] 4.7 MB"],
      ["네 projection을 GEMM 하나로 — 출력 [M, 4·768]에서 q/k/v/g가 열 구간",
       "── 수식 ──",
       "[q|k|v|g] = xa · [Wq; Wk; Wv; Wg]ᵀ + b"],
      ["qkvg = xa @ W_qkvg.t() + b_qkvg   # [3840, 3072]"],
      ["qkvg: BF16 [3,840, 3,072] 23.6 MB", "→ 코어"]),

     ("어텐션 코어 (CUDA sm_90a, attn_core.cu) · 45.6 µs (Anthropic apb_views 57.2)",
      ["qkvg 23.6 MB (q, k, v, g 열 구간)", "bias_b: BF16 [16,768,768] 18.9 MB"],
      ["CTA = (샘플, head, query 128행) · 48열 TMA 박스 · q는 레지스터",
       "bias를 누산기에 seed → QKᵀ wgmma 누산 → 추론은 running max 없음 (logit 범위 안전)",
       "ex2 → P → PV wgmma → epilogue에서 σ(g)를 곱해 q 자리에 덮어쓴다",
       "LSE도, fp32 O도 없다 — backward가 없으니 저장할 것도 없다",
       "── 수식 ──",
       "o = softmax(q kᵀ + b) v,   out = σ(g) ⊙ o"],
      ["s = q @ k.transpose(-1,-2) + bias   # 이미 log2 단위",
       "o = torch.softmax(s, -1) @ v",
       "qkvg[:, :768] = torch.sigmoid(g) * o"],
      ["gated o: qkvg의 q 열 구간에 덮어쓰기 5.9 MB", "→ Wo GEMM"]),

     ("Wo GEMM (quack) · 16.0 µs",
      ["gated o 5.9 MB", "Wo: BF16 [768,768] 1.2 MB"],
      ["── 수식 ──", "y = (σ(g) ⊙ o) Wo"],
      ["y = qkvg[:, :768] @ Wo.t()"],
      ["y: BF16 [3,840, 768] 5.9 MB", "→ resgate+AdaLN"]),

     ("resgate + AdaLN rows (Triton) · 2회 합 20.6 µs · 스텝 안에서는 HBM roof 101 %",
      ["x: FP32 잔차 [3,840, 768] 11.8 MB", "y 5.9 MB", "g2(gate), g1(다음 AdaLN scale/shift)"],
      ["잔차 갱신과 다음 서브층의 AdaLN을 한 패스에 — x를 한 번 읽고 한 번 쓴다",
       "fp32 잔차 스트림 유지 (정확도 4.4e-3, 엔진 bf16 1.1e-2)",
       "── 수식 ──",
       "x ← x + σ(gate) ⊙ y,   xa = LN(x) ⊙ (1+scale) + shift"],
      ["x  = x + torch.sigmoid(gate) * y.float()",
       "xa = layer_norm(x) * (1 + scale) + shift",
       "xa = xa.bfloat16()"],
      ["x: FP32 11.8 MB", "xa: BF16 5.9 MB", "→ 다음 GEMM"]),

     ("expand + SwiGLU GEMM (quack gemm_act) · 33.3 µs · 76 % → squeeze GEMM (cuBLAS) · 20.9 µs",
      ["xa 5.9 MB", "W_ab: BF16 [3,072, 768] 4.7 MB", "Ws: BF16 [768, 1,536] 2.4 MB"],
      ["SwiGLU를 expand GEMM의 epilogue에서 — [M, 3072] 중간값이 HBM에 안 나간다",
       "── 수식 ──",
       "h = silu(xa Waᵀ) ⊙ (xa Wbᵀ),   y = h Wsᵀ",
       "→ 다시 resgate + AdaLN(다음 블록의 AdaLN까지)"],
      ["a, b = (xa @ W_ab.t()).chunk(2, -1)",
       "h = F.silu(a) * b          # [3840, 1536]",
       "y = h @ Ws.t()"],
      ["h: BF16 [3,840, 1,536] 11.8 MB", "y: BF16 5.9 MB", "→ resgate + AdaLN → 다음 블록"]),
    ])
