seed : 0
method : AF3
translation_noise: 0.0
scheduler:
  method: AF3
  P_mean: -1.2
  P_std: 1.5
  sigma_data: 16.0
  sigma_y_max: 160.0
  sigma_y_min: 4e-4
  rho_y: 7.0
  sigma_y_phase_1_progress: 0.5
  sigma_y_phase_2_progress: 0.7
  phase_1_fraction: 0.35
  phase_2_fraction: 0.35
  sigma_R_max: 32.0
  sigma_R_min: 4e-4
  rho_R: 1.5
  sigma_T_max: 8.0
  sigma_T_min: 4e-4
  rho_T: 1.0
  use_time_augmentation: True
