seed: 0
translation_noise: 1.0
max_loss_weight: 1000.0 

scheduler:
  P_mean: -1.5
  P_std: 1.8
  sigma_data: 16.0
  sigma_y_max: 160.0
  sigma_y_min: 4e-4
  rho_y: 7.0
  sigma_y_phase_1_boundary: 64.0
  sigma_y_phase_2_boundary: 1e-2
  smooth_phase_transition: True

  sigma_R_max: 3.0
  sigma_R_min: 1e-2
  rho_R: 3.0
  sigma_T_max: 8.0
  sigma_T_min: 4e-6
  rho_T: 3.0
  use_time_augmentation: True
