from __future__ import annotations

from contextlib import ExitStack
from typing import TYPE_CHECKING, Literal

import numpy as np
import torch
from miniworld_engine.modules import LayerNorm
from pydantic import BaseModel
from team_gm.modules import DiffusionTransformer
from team_gm.modules.blocks._engine_impl import to_engine_impl
from team_gm.modules.primitives import (
    Linear,
)
from torch import nn

from miniworld.configs import SharedConfig
from miniworld.configs.models import AtomSWAConfig
from miniworld.data.features import MSAFeatures
from miniworld.loss.auxiliary import atom_distogram_target
from miniworld.modules.distogram_diffusion import (
    DistogramDiffusion,
    DistogramDiffusionConfig,
)
from miniworld.modules.heads import DistogramHead
from miniworld.modules.input_feature_embedder_esmfold2_style import (
    InputFeatureEmbedderESMFold2Style,
)
from miniworld.modules.mini_msa_module import MiniMSAModule
from miniworld.modules.mini_pairformer import MiniPairformer
from miniworld.modules.msa_util import (
    init_msa,
    init_token_single_msa,
    subsample_msa_rows,
)
from miniworld.modules.template_embedder_af3 import AF3TemplateEmbedder

if TYPE_CHECKING:
    from miniworld.data.features import (
        ReferenceFeatures,
        SchemeFeatures,
        SequenceFeatures,
        StructureFeatures,
        TemplateFeatures,
    )


class TemplateEmbedderConfig(BaseModel):
    """AF3 template embedder (``AF3TemplateEmbedder``) config for the mini trunk.

    The per-template trunk is trimul-only (MiniPairformer, miniworld-engine) — no
    triangle attention, no cuequivariance — matching the main trunk's backend.
    """

    num_channels: int = 64
    n_block: int = 2
    # Activation-checkpoint the per-template MiniPairformer blocks (None = off; 1..n_block).
    n_checkpoint_segments: int | None = None
    dropout_prob: float = 0.25
    # Output projection init: "default" (LeCun, the Protenix/OpenDDE reproduction consensus)
    # or "zero". Was MW_TEMPLATE_OUT_INIT.
    out_init: Literal["default", "zero"] = "default"
    # Per-template MiniPairformer backend. Was MW_TEMPLATE_IMPL.
    implementation: Literal["MINIWORLD_ENGINE", "PYTORCH"] = "MINIWORLD_ENGINE"


class MiniSWAModel(nn.Module):
    """Distogram-only trunk with an ESMFold2-style SWA/3D-RoPE input embedder.

    Same pair-only shape as ``distogram_only.MiniModel`` (no single track, no
    template, distogram loss through ``token_pair``), but the atom-level input
    feature embedder uses the sliding-window (or global) 3D-RoPE + QK-norm
    attention (``InputFeatureEmbedderESMFold2Style``, FlashAttention-4 on
    Hopper H100 / Blackwell B200 via ``flash_attn.cute``; falls back to flex)
    instead of the pair-bias ``DiffusionTransformer`` atom encoder. The trunk is
    the reduced ``MiniMSAModule`` (OuterProductMean + bidir trimul + transition)
    + ``MiniPairformer`` (bidir trimul + transition), which route to the cute
    (tcgen05) kernels on Hopper+.

    New-version default config (set in the model yaml): 3-block SWA atom embedder,
    4 ``MiniMSAModule`` blocks, 48 ``MiniPairformer`` blocks.
    """

    class TrunkConfig(BaseModel):
        """Configuration for trunk modules."""

        pairformer: MiniPairformer.Config
        msa_module: MiniMSAModule.Config
        n_recycle_max: int = 4
        # v1.2.0: rows the MSA module sees PER RECYCLE, drawn anew each iteration from
        # the pool the dataloader supplied (AF3 SI 3.3 / OpenFold3: 1024). None keeps
        # the legacy behaviour -- the whole pool, embedded once, shared by every cycle.
        msa_subsample_per_recycle: int | None = None
        # AF3-style template stack (adds to the pair rep before the MSA module).
        use_template: bool = False
        template_embedder: TemplateEmbedderConfig = TemplateEmbedderConfig()
        # EDM distogram-diffusion head. When set, the trunk runs as usual to produce
        # the conditioning pair rep and the distogram is GENERATED by denoising the
        # bin-index image (replacing the DistogramHead + CE). Set n_recycle_max=1 to
        # make the trunk a single conditioning pass (diffusion does the refinement).
        diffusion: DistogramDiffusionConfig | None = None

    class Config(BaseModel):
        """Configuration for the SWA-embedder mini distogram-only model."""

        shared: SharedConfig
        # non-atom parts of the input feature embedder still use this config
        input_feat_embbeder: DiffusionTransformer.Config
        # ESMFold2-style atom SWA/3D-RoPE front-end (set backend="flash" for FA4,
        # a large swa_window_size for global attention)
        atom_swa: AtomSWAConfig
        trunk: MiniSWAModel.TrunkConfig

    def __init__(self, config: Config) -> None:
        super().__init__()
        self.config = config
        self.n_recycle_max = config.trunk.n_recycle_max
        if config.trunk.diffusion is not None and self.n_recycle_max != 1:
            raise ValueError("Distogram diffusion runs one denoising trunk pass; set n_recycle_max=1")

        # ESMFold2-style SWA/3D-RoPE atom input embedder (pair-only trunk -> no single init)
        self.input_feature_embedder = InputFeatureEmbedderESMFold2Style(
            config.shared,
            config.input_feat_embbeder,
            atom_swa_config=config.atom_swa,
            produce_single_init=False,
        )

        # Pair recycle layer (single recycle dropped — single track is gone)
        self.add_pair_recycle = None if config.trunk.diffusion is not None else nn.Sequential(
            LayerNorm(
                config.shared.d_pair,
                dtype=torch.bfloat16,
                implementation=to_engine_impl(config.shared.implementation),
            ),
            Linear(
                config.shared.d_pair,
                config.shared.d_pair,
                init="zero",
                dtype=torch.bfloat16,
            ),
        )

        # AF3 template embedder — adds to the pair rep each recycle (uses the
        # current pair as query, so it is recomputed inside the recycle loop).
        self.use_template = config.trunk.use_template
        if self.use_template:
            te = config.trunk.template_embedder
            self.temp_embedder = AF3TemplateEmbedder(
                d_pair=config.shared.d_pair,
                num_channels=te.num_channels,
                num_res_class=config.shared.num_res_class,
                n_block=te.n_block,
                n_checkpoint_segments=te.n_checkpoint_segments,
                dropout_prob=te.dropout_prob,
                out_init=te.out_init,
                implementation=te.implementation,
            ).to(torch.bfloat16)

        # Minimal trunk (bidir trimul + transition; MSA folded via OuterProductMean)
        self.msa_module = MiniMSAModule(config.trunk.msa_module).to(torch.bfloat16)
        self.pairformer_blocks = MiniPairformer(config.trunk.pairformer).to(
            torch.bfloat16,
        )
        # Output: either the categorical DistogramHead (CE) or the EDM
        # DistogramDiffusion head that generates the distogram by denoising.
        self.diffusion: DistogramDiffusion | None = None
        self.distogram_head: DistogramHead | None = None
        if config.trunk.diffusion is not None:
            self.diffusion = DistogramDiffusion(
                config.shared.d_pair,
                config.shared.n_distogram_bins,
                config.trunk.diffusion,
            )
        else:
            self.distogram_head = DistogramHead(
                config.shared.d_pair,
                config.shared.n_distogram_bins,
            )

        self.rng = np.random.default_rng()
        self._forced_n_recycle: int | None = None

    def set_seed(self, seed: int) -> None:
        """Set the random seed for reproducibility."""
        self.rng = np.random.default_rng(seed)

    def _run_trunk(
        self,
        msa: MSAFeatures,
        reference: ReferenceFeatures,
        scheme: SchemeFeatures,
        sequence: SequenceFeatures,
        structure: StructureFeatures,
        template: TemplateFeatures | None,
    ) -> torch.Tensor:
        """Embed + run the recycle loop, returning the final pair rep ``token_pair``.

        With ``n_recycle_max == 1`` (the diffusion config) this is a single trunk pass
        whose output conditions the diffusion head; with more recycles it is the usual
        iterative trunk feeding the categorical head.
        """
        if self._forced_n_recycle is not None:
            n_recycle = self._forced_n_recycle
        elif self.training:
            n_recycle = self.rng.integers(1, self.n_recycle_max + 1)
        else:
            n_recycle = self.n_recycle_max

        (
            token_pair_init_bf16,
            token_single_input_bf16,
            msa_feat,
            msa_mask,
            token_mask,
        ) = self._embed(msa, reference, scheme, sequence, structure)

        token_pair = torch.zeros_like(token_pair_init_bf16)
        for i_cycle in range(n_recycle):
            with ExitStack() as stack:
                if i_cycle < n_recycle - 1:
                    stack.enter_context(torch.no_grad())
                token_pair = self._trunk_step(
                    token_pair,
                    token_pair_init_bf16,
                    token_single_input_bf16,
                    msa_feat,
                    msa_mask,
                    token_mask,
                    scheme.token_asym_id,
                    template,
                )
        return token_pair

    def forward(
        self,
        msa: MSAFeatures,
        reference: ReferenceFeatures,
        scheme: SchemeFeatures,
        sequence: SequenceFeatures,
        structure: StructureFeatures,
        template: TemplateFeatures | None = None,
        interchain_weight: float = 1.0,
    ):
        """Run the pair-only mini trunk with recycling.

        CE mode: returns distogram logits ``[B, L, L, n_distogram_bins]``.
        Diffusion mode: returns ``(edm_loss, stats)`` — the WHOLE diffusion step (trunk
        conditioning + denoiser + EDM loss) runs inside forward() so Lightning Fabric /
        DDP wraps every parameter's forward (calling a non-forward method on the wrapped
        model is disallowed and skips gradient sync).
        """
        if self.diffusion is not None:
            return self._diffusion_forward(
                msa, reference, scheme, sequence, structure, template, interchain_weight,
            )
        token_pair = self._run_trunk(
            msa, reference, scheme, sequence, structure, template,
        )
        return self.distogram_head(token_pair)

    def _diffusion_forward(
        self,
        msa: MSAFeatures,
        reference: ReferenceFeatures,
        scheme: SchemeFeatures,
        sequence: SequenceFeatures,
        structure: StructureFeatures,
        template: TemplateFeatures | None,
        interchain_weight: float,
    ) -> tuple[torch.Tensor, dict]:
        """EDM step where the TRUNK denoises the distogram bin image.

        The noised CB-distogram bin image is injected into the trunk's pair input (single
        Linear encoder, the slot recycling used) + a Fourier noise-level embedding; the
        trunk runs ONE pass; a single Linear decoder reads the denoised image back out.
        The diffusion ALWAYS uses the CB rep-atom target (sigma_data measured on it).
        """
        if structure.atom_is_rep is None:
            raise ValueError("Representative-atom distogram requires atom_is_rep features.")
        (
            token_pair_init,
            token_single_input,
            msa_feat,
            msa_mask,
            token_mask,
        ) = self._embed(msa, reference, scheme, sequence, structure)

        target, pair_mask = atom_distogram_target(
            atom_pos=structure.atom_pos,
            atom_pos_mask=structure.atom_pos_mask,
            atom_to_token_idx_map=scheme.atom_to_token_idx_map,
            num_bins=self.config.shared.n_distogram_bins,
            token_num=token_pair_init.shape[1],
            rep_atom_mask=structure.atom_is_rep,
        )
        input_mask = token_mask[:, :, None] & token_mask[:, None, :]
        input_mask = input_mask & ~torch.eye(token_mask.shape[1], device=token_mask.device, dtype=torch.bool)
        pair_mask = pair_mask & input_mask
        # Unknown target entries carry no clean signal; do not inject the overflow
        # sentinel as if it were an observed distance. Padding and diagonal are zero.
        x0 = self.diffusion.encode(target).masked_fill(~pair_mask, 0)
        sigma = self.diffusion.sample_sigma(x0.shape[0], x0.device)
        x_t = self.diffusion.add_noise(x0, sigma).masked_fill(~input_mask, 0)

        token_pair = self._diffusion_trunk(
            token_pair_init, x_t, sigma, token_single_input,
            msa_feat, msa_mask, token_mask, scheme.token_asym_id, template,
        )
        x0_hat = self.diffusion.decode_output(token_pair, x_t, sigma)
        return self.diffusion.loss(
            x0_hat, x0, pair_mask, sigma,
            token_asym_id=scheme.token_asym_id, interchain_weight=interchain_weight,
        )

    @torch.no_grad()
    def sample_distogram(
        self, msa, reference, scheme, sequence, structure, template=None,
        num_steps: int | None = None,
    ) -> torch.Tensor:
        """Generate bins from noise and conditioning, without reading target coordinates.

        Call in eval mode. Freeze the sampled MSA across Heun evaluations so the
        denoiser is a deterministic function of x and sigma throughout a trajectory.
        """
        if self.diffusion is None or self.training:
            raise ValueError("sample_distogram requires a diffusion model in eval mode")
        pair, single, msa_feat, msa_mask, token_mask = self._embed(
            msa, reference, scheme, sequence, structure,
        )
        msa_feat, msa_mask = self._msa_for_step(msa_feat, msa_mask)

        def denoise(x_t, sigma):
            features = self._diffusion_trunk(
                pair, x_t, sigma, single, msa_feat, msa_mask,
                token_mask, scheme.token_asym_id, template,
            )
            return self.diffusion.decode_output(features, x_t, sigma)

        return self.diffusion.sample(
            denoise, pair.shape[0], pair.shape[1], pair.device,
            num_steps=num_steps, token_mask=token_mask,
        )

    def _diffusion_trunk(
        self,
        token_pair_init: torch.Tensor,
        x_t: torch.Tensor,
        sigma: torch.Tensor,
        token_single_input: torch.Tensor,
        msa_feat: torch.Tensor,
        msa_mask: torch.Tensor,
        token_mask: torch.Tensor,
        token_asym_id: torch.Tensor,
        template: TemplateFeatures | None,
    ) -> torch.Tensor:
        """One trunk pass as the denoiser: inject the noised bin image (+ noise level)
        into the pair input, then MSA module + Pairformer."""
        pair_inj = self.diffusion.encode_input(
            x_t, sigma, dtype=token_pair_init.dtype,
        )
        token_pair = token_pair_init + pair_inj
        # v1.2.0: draw this pass's MSA subset from the raw pool (legacy: pass-through).
        msa_feat, msa_mask = self._msa_for_step(msa_feat, msa_mask)
        if self.use_template:
            token_pair = token_pair + self.temp_embedder(
                token_pair, template, token_asym_id, token_mask,
            )
        # MiniMSAModule owns its residual (OPM adds residual=token_pair internally), so
        # do NOT re-add token_pair here — matches main's 3d8b666 owns-residual fix.
        token_pair = self.msa_module(
            msa_feat, msa_mask, token_pair, token_single_input, token_mask, token_asym_id,
        )
        return self.pairformer_blocks(token_pair, token_mask)

    def _embed(
        self,
        msa: MSAFeatures,
        reference: ReferenceFeatures,
        scheme: SchemeFeatures,
        sequence: SequenceFeatures,
        structure: StructureFeatures,
    ):
        """Input embedding done once per microbatch (before the recycle loop).

        Returns the recycle-invariant tensors the trunk step consumes, so the
        recycle loop can be split into replayable CUDA-graph steps operating on a
        static ``token_pair`` buffer.
        """
        token_single_msa = init_token_single_msa(
            msa,
            sequence,
            num_res_class=self.config.shared.num_res_class,
        )
        # input feature embedding — token_single_init is None (single-track off)
        (
            token_single_input,
            _,
            token_pair_init,
        ) = self.input_feature_embedder(
            token_single_msa,
            reference,
            scheme,
            structure,
        )
        if self.config.trunk.msa_subsample_per_recycle is None:
            # legacy: embed the whole pool once, every recycle reuses it
            msa_feat, msa_mask = init_msa(
                msa,
                num_res_class=self.config.shared.num_res_class,
                dtype=torch.bfloat16,
            )
        else:
            # v1.2.0: hand the raw pool to the recycle loop; each ``_trunk_step``
            # draws its own rows and embeds only those (see ``_msa_for_step``).
            msa_feat, msa_mask = msa, None
        return (
            token_pair_init.to(torch.bfloat16),
            token_single_input.to(torch.bfloat16),
            msa_feat,
            msa_mask,
            structure.token_mask,
        )

    def _msa_for_step(self, msa_feat, msa_mask):
        """Resolve what the MSA module sees in THIS recycle.

        Legacy path: ``msa_feat`` is the embedded pool from ``_embed`` -> pass through.
        v1.2.0 path: ``msa_feat`` is the raw :class:`MSAFeatures` pool -> draw
        ``trunk.msa_subsample_per_recycle`` rows (valid first, query kept, fresh rows
        on every call and every CUDA-graph replay) and embed just those. Static
        output shape either way.
        """
        if not isinstance(msa_feat, MSAFeatures):
            return msa_feat, msa_mask
        subset = subsample_msa_rows(msa_feat, self.config.trunk.msa_subsample_per_recycle)
        return init_msa(
            subset,
            num_res_class=self.config.shared.num_res_class,
            dtype=torch.bfloat16,
        )

    def _trunk_step(
        self,
        token_pair,
        token_pair_init_bf16,
        token_single_input_bf16,
        msa_feat,
        msa_mask,
        token_mask,
        token_asym_id,
        template: TemplateFeatures | None,
    ):
        """One recycle iteration of the trunk (template → MSA → Pairformer).

        Pure function of ``token_pair`` and the recycle-invariant embeddings, so a
        single capture of this step (no_grad or grad) is replayable for any recycle
        count: replay under no_grad ``n_recycle-1`` times, then once with grad.
        """
        token_pair = token_pair_init_bf16 + self.add_pair_recycle(token_pair)
        msa_feat, msa_mask = self._msa_for_step(msa_feat, msa_mask)

        # AF3 trunk order: template → MSA → Pairformer.
        if self.use_template:
            token_pair = token_pair + self.temp_embedder(
                token_pair,
                template,
                token_asym_id,
                token_mask,
            )

        token_pair = self.msa_module(
            msa_feat,
            msa_mask,
            token_pair,
            token_single_input_bf16,
            token_mask,
            token_asym_id,
        )

        return self.pairformer_blocks(
            token_pair,
            mask=token_mask,
        )
