data:
  train_db:
    cif_db_path: /home/psk6950/data/BioMolDBv2_2024Oct21/cif_20210930_res9.lmdb
    a3m_db_path: /home/psk6950/data/BioMolDBv2_2024Oct21/slim_a3m.lmdb
    edge_id_to_cif_ids_path: /home/psk6950/data/BioMolDBv2_2024Oct21/metadata/graph_split_20210930_res9/train_edges.tsv
    load_all_msa: False
    
  valid_db:
    cif_db_path: /home/psk6950/data/BioMolDBv2_2024Oct21/cif_20210930_res9.lmdb
    a3m_db_path: /home/psk6950/data/BioMolDBv2_2024Oct21/slim_a3m.lmdb
    edge_id_to_cif_ids_path: /home/psk6950/data/BioMolDBv2_2024Oct21/metadata/graph_split_20210930_res9/valid_edges.tsv
    load_all_msa: False

  edge_weight:
    PP_edge: 1.0
    PN_edge: 1.0
    PL_edge: 0.666
    NN_edge: 1.0
    NL_edge: 0.666
    LL_edge: 0.0
    eta: 0.9
    decay: 0.999
    init_score: 1.0
    init_freq: 0.0
    device: "cpu"

  crop:
    contiguous_prob: 0.2
    spatial_prob: 0.4
    interface_prob: 0.4
    crop_length: 384

  msa:
    n_samples: 1
    max_msa_depth: 384


model:
  common:
    d_token_single: 384
    d_token_single_input: 449  # 441 = 384 + 32 + 32 + 1
    d_token_single_diffusion: 768
    d_token_pair: 128
    d_time: 256
    d_msa: 64
    d_atom_single: 128
    d_atom_pair: 16
    num_res_class: 32
    r_max: 32
    s_max: 2
    implementation: triton
    use_checkpoint: False


  contact_map:
    max_inputs_pos: 64
    max_inputs_neg: 64
    pairformer:
      n_block: 2
      d_single: ${model.common.d_token_single}
      d_pair: ${model.common.d_token_pair}
      d_hidden_tri_multi: 128
      d_hidden_tri_attention: 32
      n_head_tri_attention: 4
      n_head_attention: 16
      p_drop: 0.25
      use_single: False
      use_single_cond: False
      use_self_attention: True
      implementation: triton
      pair_moe_experts: 1
      pair_moe_topk: 1
      single_moe_experts: 1
      single_moe_topk: 1

  trunk:
    n_recycle_max: 1 # 4
    pairformer: 
      n_block: 4
      d_single: ${model.common.d_token_single}
      d_pair: ${model.common.d_token_pair}
      d_hidden_tri_multi: 128
      d_hidden_tri_attention: 32
      n_head_tri_attention: 4
      n_head_attention: 16
      p_drop: 0.25
      use_single: True
      use_single_cond: False
      # use_self_attention: True
      use_self_attention: False
      # implementation: pytorch
      implementation: triton

    msa_module: 
      n_block: 2
      d_msa: 64
      d_pair: ${model.common.d_token_pair}
      d_hidden_msa: 32
      d_hidden_tri_multi: 128
      d_hidden_tri_attention: 32
      n_head_tri_attention: 4
      n_head_attention: 16
      p_drop_msa: 0.15
      p_drop: 0.25
      # use_self_attention: True
      use_self_attention: False
      implementation: triton
  diffusion:
    frequency_embedding_size: 256
    n_block_atom: 3
    n_block_token: 4
    n_head_atom: 4
    n_head_token: 24
    n_transition_expand: 2
    n_transition_block: 2
    implementation: triton
    use_beta: False
    # dtype: float32
  precision:
    input: torch.float32
    use_scaler: False  # Use GradScaler for mixed precision training
    default:
      op_dtype: torch.float32  # Default operation dtype
      out_dtype: torch.float32  # Default output dtype
    precision_map:
      "msa_module": 
        op_dtype : torch.bfloat16
        out_dtype: torch.bfloat16 
      "pairformer_blocks": 
        op_dtype : torch.bfloat16
        out_dtype: torch.bfloat16  # Precision for pairformer blocks
      "diffusion_module":
        op_dtype : torch.float32
        out_dtype: torch.float32  # Precision for diffusion modules


loss:
  diffusion_loss: 4.0
  distogram_loss: 0.03


diffuser:
  seed : 0
  method : AF3
  scheduler:
    method: AF3
    P_mean: -1.2
    P_std: 1.5
    sigma_data: 16.0
    sigma_max: 160.0
    sigma_min: 4e-4
    rho: 7.0
    use_time_augmentation: True

experiment:
  comment: cmap_template_af3 wo msa_module (pos64, neg64)

  # Training arguments
  num_batch: 1
  num_epoch: 1000
  # max_lr: 1.8e-3
  max_lr: 1e-4
  min_lr: 1e-4
  warmup_steps: 0
  decay_steps: 5e4
  self_condition: False
  compile: False
  num_augment: 48
  train_item: 2400
  valid_item: 640

  # Validation arguments
  eval_freq: 10
  eval_sample_num: 1
  eval_input_num: 50
  eval_timesteps: 100
  grad_clip_max_norm: 10.0
  grad_accum_steps: 1
  num_workers: 4
  prefetch_factor: 8
  use_ema: False
