data:
  DB_PATH: /home/psk6950/data/

  train_preprocessing:
    cif_db_path: ${data.DB_PATH}/MiniWorld/multistate/seqID_to_cifmols_filtered.lmdb
    a3m_db_path: ${data.DB_PATH}/BioMolDBv2_2024Oct21/slim_a3m.lmdb
    tmp_dir: ${data.DB_PATH}/MiniWorld/multistate/data_tmp/monomer/train/
    cluster_ids_path: ${data.DB_PATH}/MiniWorld/multistate/train_valid_split/train_clusters.txt
    cluster_id_to_seq_ids_path: ${data.DB_PATH}/MiniWorld/multistate/clusterID_to_seqIDs.npz
    seq_id_to_seq: ${data.DB_PATH}/BioMolDBv2_2024Oct21/fasta/protein_wo_signalp.fasta
    signalp_dir: ${data.DB_PATH}/BioMolDBv2_2024Oct21/signalp/
  valid_preprocessing:
    cif_db_path: ${data.DB_PATH}/MiniWorld/multistate/seqID_to_cifmols_filtered.lmdb
    a3m_db_path: ${data.DB_PATH}/BioMolDBv2_2024Oct21/slim_a3m.lmdb
    tmp_dir: ${data.DB_PATH}/MiniWorld/multistate/data_tmp/monomer/valid/
    cluster_ids_path: ${data.DB_PATH}/MiniWorld/multistate/train_valid_split/valid_clusters.txt
    cluster_id_to_seq_ids_path: ${data.DB_PATH}/MiniWorld/multistate/clusterID_to_seqIDs.npz
    seq_id_to_seq: ${data.DB_PATH}/BioMolDBv2_2024Oct21/fasta/protein_wo_signalp.fasta
    signalp_dir: ${data.DB_PATH}/BioMolDBv2_2024Oct21/signalp/

  crop:
    contiguous_prob: 1.0
    spatial_prob: 0.0
    interface_prob: 0.0
    crop_length: 384
    level: residue

  msa:
    n_samples: 1
    max_msa_depth: 384

  kmer_fast_align:
    kmer_index: ${data.DB_PATH}/kmer_align/kmer_index.tsv
    fasta: ${data.DB_PATH}/fasta/protein_wo_signalp.fasta
    kmer_threshold: 0.2
    gap_split: 15
    max_mismatch: 15
    max_indel: 5
    align_num: -1
    align_thr: 0.9
    seed: 1123
    
  multistate:
    n_prefilter: 48
    n_samples: 48
    temperatures: 1.0
    consensus_ratio: 0.9
    consensus_filter: 0.9

model:
  common:
    d_token_single: 384
    d_token_single_input: 449
    d_token_single_diffusion: 768
    d_token_pair: 128
    d_time: 256
    d_msa: 64
    d_atom_single: 128
    d_atom_pair: 16
    num_res_class: 32
    r_max: 32
    s_max: 2
    implementation: triton
    use_checkpoint: False
    to_bias_init: zero
    norm: qk

  trunk:
    n_recycle_max: 1
    pairformer: 
      n_block: 8
      d_single: ${model.common.d_token_single}
      d_pair: ${model.common.d_token_pair}
      d_hidden_tri_multi: 128
      d_hidden_tri_attention: 32
      n_head_tri_attention: 4
      n_head_attention: 16
      p_drop: 0.25
      use_single: False
      use_single_cond: False
      use_self_attention: True
      implementation: triton
      pair_moe_experts: 1
      pair_moe_topk: 1
      single_moe_experts: 1
      single_moe_topk: 1

    msa_module: 
      n_block: 4
      d_msa: 64
      d_pair: ${model.common.d_token_pair}
      d_hidden_msa: 32
      d_hidden_tri_multi: 128
      d_hidden_tri_attention: 32
      n_head_tri_attention: 4
      n_head_attention: 16
      p_drop_msa: 0.15
      p_drop: 0.25
      use_self_attention: False
      implementation: triton

  diffusion:
    frequency_embedding_size: 256
    n_block_atom: 3
    n_block_token: 4
    n_head_atom: 4
    n_head_token: 24
    n_transition_expand: 2
    n_transition_block: 2
    implementation: triton
    use_beta: True
    pair_moe_experts: 1
    pair_moe_topk: 1
    token_single_moe_experts: 1
    token_single_moe_topk: 1
    atom_single_moe_experts: 1
    atom_single_moe_topk: 1

  precision:
    bf16: True
    tf32: False

experiment:
  comment: contactmap_generation_v0.0.0_d3pm
  name: contactmap_generation_v0.0.0_d3pm
  overfitting: False
  overfitting_dir: null
  train_item: 25600
  valid_item: 2560
  num_batch: 1
  num_epoch: 1000
  optimizer: AdamW
  max_lr: 1.0e-4
  min_lr: 1.0e-5
  weight_decay: 0.01
  warmup_steps: 5000
  decay_steps: 5000000
  decay_factor: 0.95
  self_condition: True
  compile: False
  num_augment: 8
  eval_freq: 10
  eval_sample_num: 5
  eval_timesteps: 100
  eval_input_num: 50
  grad_clip_max_norm: 1.0
  grad_accum_steps: 256
  num_workers: 4
  prefetch_factor: 4
  seed: 0
  use_ema: True
  ema_decay: 0.999
  bce_pos_weight: 8.0
  long_range_min_seq_sep: null
  long_range_sigmoid_k: null
  long_range_sigmoid_amp: null

discrete_diffusion:
  method: d3pm
  d3pm_scheduler:
    method: D3PM
    num_train_timesteps: 1000
    beta_start: 1.0e-4
    beta_end: 2.0e-2
    beta_schedule: linear
    transition_mode: uniform
    mask_class: null
  d3pm_diffuser:
    method: D3PM
    seed: 0
    num_classes: 2
    enforce_symmetric: True
  d3pm_solver:
    method: Euler
    seed: 0
