from pathlib import Path
import json,re,shutil
R=Path('/home/psk6950/MiniWorld');D=R/'runs/anthropic_ln_dropout_20260919';A=R/'runs/anthropic_adoption_20260919'
labels=[('fused-dropout','입력 LN 융합 · dropout 파생 K3'),('anthropic-share','분리 · Anthropic LN · x_n 공유'),('anthropic-recompute','분리 · Anthropic LN · K3 재계산'),('triton-share','분리 · Triton LN · x_n 공유'),('triton-recompute','분리 · Triton LN · K3 재계산')]
def table(name):
 rs=json.loads((D/name).read_text());assert len(rs)==2
 return '<div class="table-wrap"><table><thead><tr><th>경로</th><th>L384 (µs)</th><th>L768 (µs)</th></tr></thead><tbody>'+''.join('<tr><td>'+label+'</td>'+''.join('<td>%.2f</td>'%r['full'][k]['median_us'] for r in rs)+'</tr>' for k,label in labels)+'</tbody></table></div>'
sec='''<!-- DROPOUT_BEGIN --><section class="panel" id="dropout-ln"><span class="pill green">최신 · dropout 25%</span><h2>입력 LN 공유 vs K3 재계산 — dropout 재튜닝</h2><p>출력 LN은 항상 융합. backward 저장 없는 forward 비교를 유지하고 row dropout 25%를 추가했다. 변경된 공유형·재계산형 K3를 L384/L768 각각 <b>44개 설정</b>으로 재튜닝했다. 변경 없는 LN/K1 설정은 유지했다.</p><div class="flow"><div><b>공유형</b>입력 LN → x_n → K1<br>K3: x_n + residual 별도 TMA → dropout → residual</div><div><b>재계산형</b>입력 LN → x_n → K1<br>K3: 원본 x → 입력 LN 재계산 → dropout → residual</div></div><h3>전체 forward · 매 replay 새 mask 생성 포함</h3>'''+table('rng-results.json')+'''<h3>전체 forward · 고정 공통 mask, RNG 제외</h3>'''+table('results.json')+'''<p><b>결론:</b> 공유/재계산 전체 시간 차이는 1% 미만이며 LN 구현·shape에 따라 순위가 바뀐다. 재계산의 일관된 우위는 확인되지 않았다. 특히 L768 RNG 포함 측정의 표준편차는 약 7–12µs이므로 작은 중앙값 차이를 확정적 이득으로 해석하지 않는다.</p><h3>K3 재튜닝 효과 (동일 dropout 커널)</h3><table><tr><th>경로</th><th>L384 기존 → 재튜닝 (µs)</th><th>L768 기존 → 재튜닝 (µs)</th></tr><tr><td>공유형</td><td>89.17 → 84.82 (4.9% 감소)</td><td>316.04 → 291.40 (7.8% 감소)</td></tr><tr><td>재계산형</td><td>84.66 → 83.76 (1.1% 감소)</td><td>296.92 → 283.15 (4.6% 감소)</td></tr></table><p>선택 설정 (BI,BJ,NSLOT,NACC,R240_SWITCH,LN_SERIAL): 공유384=(1,128,4,1,0,1), 공유768=(2,64,6,2,0,0), 재계산384=(2,64,4,1,0,0), 재계산768=(1,128,4,1,1,0).</p><p>H100 node02 · B1 C128/H256 BF16 · 양방향 packed cuBLAS · mask/residual 포함 · weight prepacked · CUDA Graph 200회 × 20라운드, 순서 순환·역전. 첫 행은 원본 K1 + dropout 추가·재튜닝 K3로, 변경 없는 Anthropic 원본 수치가 아니다. dropout scale [L,C]는 첫 pair 축을 공유한다. BF16 gated update → BF16 dropout → residual 순서이며 기존 학습 F567 저장/반올림 계약이나 전체 학습 시간 측정이 아니다.</p><p>44×4 후보 parity 통과. 최종 설정 L64/72 Torch reference·공유/재계산 비트 일치·0/1 mask·graph mask 갱신 검증 통과. memcheck 0 errors, racecheck 0 hazards. production 배선은 변경하지 않았다.</p><p><a href="assets/dropout-rng-results.json">RNG 포함 원자료</a> · <a href="assets/dropout-results.json">고정 mask·설정 원자료</a> · <a href="assets/dropout-validation.json">검증</a> · <a href="assets/dropout-README.md">방법·재현</a></p></section><!-- DROPOUT_END -->'''
for p in (R/'ANTHROPIC_TRIMUL.html',A/'web/trimul.html',A/'site/dist/trimul.html'):
 s=p.read_text();s=re.sub(r'<!-- DROPOUT_BEGIN -->.*?<!-- DROPOUT_END -->','',s,flags=re.S);s=s.replace('<main>','<main>'+sec,1)
 if 'href="#dropout-ln"' not in s:s=s.replace('<nav>','<nav><a href="#dropout-ln">Dropout 재튜닝</a>',1)
 p.write_text(s)
for d in (A/'web/assets',A/'site/dist/assets'):
 for f in ('rng-results.json','results.json','validation.json','README.md'):shutil.copyfile(D/f,d/('dropout-'+f))
print('Updated 3 pages and evidence assets')
