from pathlib import Path
import json,re,shutil
R=Path('/home/psk6950/MiniWorld');D=R/'runs/anthropic_b1b4_cuda_20260919';A=R/'runs/anthropic_adoption_20260919'
rs=json.loads((D/'final-results.json').read_text());assert len(rs)==2
rows=''
for r in rs:
 for k,label in [('b1b4','B1–B4'),('bwd','전체 backward')]:
  a=r['times']['baseline-'+k]['median_us'];b=r['times']['cuda-'+k]['median_us'];rows+=f'<tr><td>{r["N"]}</td><td>{label}</td><td>{a:.2f}</td><td>{b:.2f}</td><td>+{(b/a-1)*100:.1f}%</td></tr>'
svg='''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="780" viewBox="0 0 1200 780"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker><style>text{font-family:Arial,sans-serif;fill:#16304b} .h{font-size:23px;font-weight:bold}.t{font-size:17px}.s{font-size:15px}.a{stroke:#64748b;stroke-width:2;fill:none;marker-end:url(#arrow)}</style></defs><rect width="1200" height="780" fill="#f7f9fc"/><text x="35" y="42" class="h">B1–B4 · CUDA 단일 launch 실험 · H100</text><text x="35" y="72" class="t">dropout 25% · BF16 · C128/H256 · 기존보다 느림, 실험 경로 유지</text><rect x="35" y="97" width="1130" height="73" rx="12" fill="#deebf7"/><text x="55" y="126" class="t">저장 입력: dy · projection · gate · dropout scale · x_n · normalized_tri · tri · LN mean/rstd/γ · Wp</text><text x="55" y="152" class="s">TMA → shared memory · Anthropic ldmatrix / stmatrix / WGMMA RS 방식 차용</text><rect x="25" y="198" width="1150" height="380" rx="16" fill="none" stroke="#346fa3" stroke-width="3"/><text x="45" y="228" class="h">fused_b1b4 : CUDA kernel 1회</text><rect x="45" y="252" width="535" height="207" rx="10" fill="#e0f2fe"/><text x="65" y="282" class="h">행별 gradient CTA</text><text x="65" y="318" class="t">B1: dropout + gate 미분 → dp / dg</text><text x="65" y="351" class="t">B3a: dp × Wp → BF16 dnorm (on-chip)</text><text x="65" y="384" class="t">B4: LN 미분 → dtri + dγ/dβ 부분합</text><text x="65" y="427" class="s">dp와 dnorm의 global-memory 버퍼 제거</text><rect x="605" y="252" width="550" height="207" rx="10" fill="#eee8ff"/><text x="625" y="282" class="h">Weight-gradient CTA · 2 warpgroups</text><text x="625" y="318" class="t">B1 미분을 타일별 재계산</text><text x="625" y="351" class="t">B2: x_nᵀ × dg → dWg 부분합</text><text x="625" y="384" class="t">B3b: dpᵀ × normalized_tri → dWp 부분합</text><text x="625" y="427" class="s">입력 재읽기 발생 · 모든 데이터를 한 번만 읽는 구조는 아님</text><rect x="45" y="479" width="1110" height="76" rx="10" fill="#fff1cf"/><text x="65" y="508" class="t">Global FP32 부분합 + 완료 counter → 마지막 도착 CTA가 최종 합산</text><text x="65" y="537" class="s">LN: 2단계 그룹 합산 · weight: split-K 합산 · counter는 완료 후 reset · CTA 간 spin-wait 없음</text><path class="a" d="M310 170 V250"/><path class="a" d="M885 170 V250"/><path class="a" d="M310 459 V477"/><path class="a" d="M885 459 V477"/><path class="a" d="M600 578 V607"/><rect x="35" y="610" width="1130" height="75" rx="10" fill="#dff4e7"/><text x="55" y="642" class="t">출력: dg (B9용) · dWg · dtri (B6용) · dγ · dβ · dWp</text><text x="55" y="671" class="s">기존 나머지 backward와 연결 · residual gradient는 dy alias · 저장 정책 변경 없음</text><text x="35" y="726" class="t">결과: launch 수·중간 버퍼 감소만으로 속도 우위를 얻지 못함. 현재 병목은 낮은 실행 효율.</text><text x="35" y="757" class="s">workspace/Wp packing/RNG 생성은 측정 제외 · production 배선 변경 없음</text></svg>'''
(R/'ANTHROPIC_B1_B4_BACKWARD.svg').write_text(svg)
sec='''<!-- B1B4_BEGIN --><section class="panel" id="b1b4-cuda"><span class="pill">최신 · CUDA backward 융합 실험</span><h2>B1–B4를 한 kernel에 넣은 결과</h2><p><b>구현·정확성 검증 완료. 현재는 기존보다 느려서 기본 경로로 채택하지 않음.</b> Anthropic native v5의 TMA·WGMMA RS·ldmatrix/stmatrix 배치에서 출발한 새 backward다. Anthropic에서 제공한 backward는 아니다.</p><img src="assets/b1b4-backward.svg" alt="B1부터 B4까지 단일 CUDA launch의 행별 gradient와 weight gradient 및 부분합 배선" style="width:100%;height:auto;background:#f7f9fc;border-radius:12px"/><div class="table-wrap"><table><thead><tr><th>L</th><th>구간</th><th>기존 Triton/cuBLAS (µs)</th><th>단일 CUDA (µs)</th><th>시간 증가</th></tr></thead><tbody>'''+rows+'''</tbody></table></div><p>초기 L384 약 1,570µs → BF16 pair/stmatrix 약 827µs → shared-memory 축소 약 634µs → 2 warpgroup 약 526µs → 최종 약 488µs. 초기 구현 대비 약 3.2배 개선했지만 기존 295µs보다 느리다. 큰 accumulator로 입력 재사용을 늘린 버전과 fragment LN 미분도 시험했으나 더 느렸다.</p><p>최종 선택: split-K=64, LN reduction group=64, compact shared memory=80KiB, CTA당 weight warpgroup=2. 24개 최종 후보/shape 및 상위 4개 재측정. 입력 gradient는 WGMMA accumulator 1개를 순차 재사용한다. dp·dnorm의 global 버퍼는 제거했지만 B1 입력 재읽기와 global 부분합은 남는다.</p><p><b>NCU:</b> 최초 구현 HBM 약 11.3%, tensor-active 약 1.62%, active warps 약 6.25%. roofline에 도달한 상태가 아니다. 최종 L384는 HBM 약 41.0%, tensor-active 약 5.47%, active warps 약 17.3%, shared-memory 상한 2 CTAs/SM. SASS에서 TMA·WGMMA 확인, spill 0. 원자료는 아래 JSON에 기록. 큰 버퍼를 없애는 것과 GPU 실행 효율을 높이는 것은 별도로 검증해야 한다.</p><p>node02 H100 · B1 C128/H256 BF16 · dropout 25% · 동일 저장값/동일 나머지 backward · Graph 80회 × 20 교대 라운드. 공통 고정 mask, RNG/weight packing/workspace 초기화 제외. 전체 backward도 실제로 B1–B4만 교체해 직접 측정. baseline cache miss는 기존 3개 후보 fallback이므로 전체 baseline 재튜닝 완료를 뜻하지 않는다.</p><p>Plan은 단일 stream에서 순차 재사용하며 동시 호출에는 별도 workspace가 필요하다. 최종 gradient 비교·mask 변경·Graph 반복 재생·counter reset·memcheck/racecheck 결과를 원자료에 남겼다.</p><p><a href="assets/b1b4-final-results.json">측정·후보·전체 gradient 오차</a> · <a href="assets/b1b4-validation.json">검증</a> · <a href="assets/b1b4-ncu-final-summary.json">최종 NCU</a> · <a href="assets/b1b4-README.md">설계·제약·재현</a></p></section><!-- B1B4_END -->'''
for p in (R/'ANTHROPIC_TRIMUL.html',A/'web/trimul.html',A/'site/dist/trimul.html'):
 s=p.read_text();s=re.sub(r'<!-- B1B4_BEGIN -->.*?<!-- B1B4_END -->','',s,flags=re.S);s=s.replace('<main>','<main>'+sec,1)
 if 'href="#b1b4-cuda"' not in s:s=s.replace('<nav>','<nav><a href="#b1b4-cuda">B1–B4 CUDA</a>',1)
 p.write_text(s)
for d in (A/'web/assets',A/'site/dist/assets'):
 (d/'b1b4-backward.svg').write_text(svg)
 for f in ('final-results.json','validation.json','ncu-final-summary.json','README.md'):shutil.copyfile(D/f,d/('b1b4-'+f))
print('Updated B1–B4 experiment dashboard')
